#!/bin/sh

if [ $(id -u) = 0 ]; then
	printf "$(basename $0): do not run as root.\n"
	exit 1
fi

if [ $(id -u) != 0 ]; then
	if [ -f /usr/bin/sudo ]; then
		sudo=1
	fi
fi

bin_path=/usr/bin
var_path=/var

if [ $(uname -o) != "GNU/Linux" ]; then
	bin_path=$PREFIX/bin
	var_path=$prefix/var
fi

opt=$(getopt -n $(basename $0) -o hciu -l help,clean,install,uninstall -- "$@")

if [ $? -ne 0 ]; then
	printf "Try '$(basename $0) --help' for more information.\n"
	exit
fi

eval set -- $opt

while true; do
	if [ "$1" = "--" ]; then
		shift
		optarg=$@
		break
	else
		case $1 in
			--install|-i)
				install=1
			;;
			--help|-h)
				help=1
			;;
			--uninstall|-u)
				uninstall=1
			;;
			--clean|-c)
				clean=1
			;;
			*)
				break
			;;
		esac
	fi
	shift
done

this_dir=$(dirname $(realpath $0))
src_dir=$this_dir/src
out_dir=$this_dir/out
out_program=$out_dir/$(basename $this_dir).sh

if [ ! -d $out_dir ]; then
	if [ -f $out_dir ]; then
		rm -rf $out_dir
	else
		mkdir $out_dir
	fi
fi

if [ ! -z $help ]; then
	exit 1
fi

if [ ! -z $clean ]; then
	printf "$(basename $0): clean\n"
	rm -rf $out_dir
	printf "complete.\n"
	exit 1
fi

if [ ! -z $uninstall ]; then
	printf "$(basename $0): uninstall\n"
	if [ ! -z $sudo ]; then
		if [ -f $bin_path/alpine ]; then
			sudo rm -rf $bin_path/alpine
		fi
		if [ -d $var_path/lib/alpine ]; then
			sudo rm -rf $var_path/lib/alpine
		fi
	else
		if [ -f $bin_path/alpine ]; then
			rm -rf $bin_path/alpine
		fi
		if [ -d $var_path/lib/alpine ]; then
			rm -rf $var_path/lib/alpine
		fi
	fi
	printf "complete.\n"
	exit 1
fi

put () {
	if [ -z $1 ]; then
		return 0
	fi
	if [ ! -f $* ]; then return 0; fi
	printf "\n" >> $out_program
	cat $@ >> $out_program
	printf "\n" >> $out_program
	return 1
}

printf "#!/bin/sh\n" > $out_program

printf "# Build Date $(date)\n" >> $out_program

put src/env.sh

put src/init.sh

put src/opt.sh

for file in src/function/*.sh; do
	put $file
done

put src/main.sh

chmod +x $out_program
chown $USER $out_program

if [ ! -z $install ]; then
	printf "$(basename $0): install\n"
	if [ ! -z $sudo ]; then
		sudo cp $out_program $bin_path/alpine
		sudo chmod +x $bin_path/alpine
		if [ ! -d $var_path/lib/alpine ]; then
			sudo mkdir $var_path/lib/alpine
		fi
	else 
		cp $out_program $bin_path/alpine
		chmod +x $bin_path/alpine
		if [ ! -d $var_path/lib/alpine ]; then
			mkdir $var_path/lib/alpine
		fi
	fi
	printf "complete.\n"
	exit 1
fi

if [ ! -z $release ]; then
	exit
fi