#!/bin/sh
dir=$(dirname $(realpath $0))
os=$(uname -o)
if [ "$os" = "GNU/Linux" ]; then
	if [ $(id -u) != 0 ]; then
		printf "$(basename $0): permission denied\n"
		exit
	fi
fi

if [ ! -f $dir/out/alpine ]; then
	printf "install: error: do the build first\n"
	exit 1
fi

if [ "$os" = "Android" ]; then
	cp $dir/out/alpine $PREFIX/bin/alpine
	chmod +x $PREFIX/bin/alpine
elif [ "$os" = "GNU/Linux" ]; then
	cp $dir/out/alpine /usr/bin/alpine
	chmod +x /usr/bin/alpine
fi
